config/routes.rb
Rails.application.routes.draw do

  resources :todos
  resources :users

  get '/', to: 'todos#index'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :title, presence:true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, 
        presence: true,
        uniqueness: true,
        format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Saisir un email valide." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by(email: params[:email])
        session[:user_id] = @user.id
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController


    before_action :set_todo, only: [:update, :edit, :show, :destroy]


    def index
        @todos = Todo.all
    end
    
    def new
        @todo = Todo.new
    end

    def show
        
    end
    def create
        todo = Todo.create(todo_params)
        redirect_to todo_path(todo.id)
        
    end

    def update
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def destroy
        @todo.destroy
        redirect_to todos_path
    end

    private

    def todo_params
        params.require(:todo).permit(:title, :description, :date)
    end

    def set_todo
        @todo = Todo.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to todos_path
            
        else
            message = "Email déjà utilisé"
            redirect_to new_user_path, notice: message
        end
    end

    def show
        @user = User.find(params[:id])
    end


    private 

    def user_params
        params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])  if !!session[:user_id]
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1> Editer la todo  </h1>

<%= form_for @todo do |f| %>
    <div class='form-group'>
        <label> Titre de la todo </label>
        <%= f.text_field :title, class: 'form-control' %>
        <label> Description de la todo </label>
        <%= f.text_area :description, class: "form-control" %>
        <label> Date limite pour faire la todo </label>
        <%= f.date_select(:date, :order => [:month, :day, :year]) %>
            <button type="submit" class="btn btn-primary mt-3"> Modifier la todo </button>
        </div>
    </div>
<% end %>

app/views/todos/index.html.erb
<% if !current_user %>
<h1> Bienvenue ! Sur ce site tu peux créer des todos listes !</h1>
<a href="<%= login_path %>" class="btn btn-info"> Se connecter </a>
<a href="<%= new_user_path %>" class="btn btn-info"> Créer un compte </a>

<% else %>
<h1>Hello <%= current_user.email%> </h1>

<h2>La liste de mes todos </h2>
<% @todos.each do |todo| %>
    <div class="card m-3" style="width: 18rem;">
        <div class="card-body">
            <h4 class="card-title"><%= todo.title %></h4>
            <p class="card-text"><%= todo.description %></p>
            <p class="card-text"> Date limite : <%= todo.date %></p>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" !checked>
                <label class="form-check-label" for="defaultCheck1">
                    Todo effectuée
                </label>
            </div>
            <p>
                <a href="<%= todo_path(todo.id) %>" class="card-link"> Voir la suite </a>
                <a href="<%= edit_todo_path(todo.id) %>" class="card-link"> Editer </a>
                <a href="<%= todo_path(todo.id) %>" class="btn btn-outline-danger mt-5" data-confirm="Etes vous sûr ?" data-method="DELETE"> Supprimer </a>
            </p>
        </div>
    </div>
<% end %>
<p class="mt-5">
    <a href="<%= new_todo_path %>" class="btn btn-warning"> Créer une todo </a>
</p>
<%end%>

app/views/todos/new.html.erb
<h1> Créer une todo  </h1>

<%= form_for @todo do |f| %>
    <div class='form-group'>
        <label> Titre de la todo </label>
        <%= f.text_field :title, class: 'form-control' %>
        <label> Descritpion de la todo </label>
        <%= f.text_area :description, class: "form-control" %>
        <label> Date limite pour faire la todo </label>
        <%= f.date_select(:date, :order => [:month, :day, :year]) %>
        <div class="form-group"> 
            <button type="submit" class="btn btn-primary mt-3"> Créer la todo </button>
        </div>
    </div>
<% end %>

app/views/todos/show.html.erb
<h1> <%= @todo.title %> </h1>

<p> <%= @todo.description%> </p>
<p> Date limite : <%= @todo.date%> </p>

<p> <a href="<%= todos_path %>" class="btn btn-primary"> Revenir à la liste des todos </a>  </p>

app/views/users/new.html.erb
<h3> Créer un compte </h3>

<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit "Créer mon compte" %>
<% end %>